---

# Pi 1 or Zero
- name: Install armv6l release of grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana-rpi_{{ grafana_version }}_armhf.deb
  when: 
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - ansible_architecture == "armv6l"

# Pi 2 - 4 32bit
- name: Install armv7l release of grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_armhf.deb
  when: 
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - ansible_architecture == "armv7l"

# Eg Pi4 in 64bit mode / AWS / Apple Silicon
- name: Install ARM 64bit release of grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_arm64.deb
  when: 
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - ansible_architecture == "aarch64"

# x86_64
- name: Install ARM x86_64 release of grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb
  when: 
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - ansible_architecture == "x86_64"
    